### ISSUE TITLE
Link to documentation is down

### ISSUE THREAD

**Issue by LucaCappelletti94** [mapio/py-web-graph#6]
Hello,

could you please upload the documentation somewhere accessible?

Thanks for porting webgraph to python!
Luca

**Comment by mapio** [comment]
The docs were included in the repo https://github.com/mapio/py-web-graph/tree/a745efb2898d8fa42262ef6aa1f8dae50e9bfb2b/docs/_build/html I've just moved them where GitHub Pages can see them (and updated a couple of links). 

You can see the docs at https://mapio.github.io/py-web-graph/ but the project is not maintained, so things may be very broken and not working given more modern versions of Python, Jython and WebGraph (not to mention that UbiGraph is nowhere to be found nowdays).

**Comment by LucaCappelletti94** [comment]
Ok, thank you very much nontheless!

Have a nice day!
