### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by raulpuric** [mapio/py-web-graph#8]
Hi I'm trying to install and run a webgraph server.

I've installed the latest jython as I couldn't find version 2.5b2 .
I also installed the webgraph and LAW libraries using your other common crawl project [installation scripts ](https://github.com/commoncrawl/cc-webgraph/blob/master/src/script/webgraph_ranking/install_webgraph.sh).

However, I can't import any of the `it.unimi.dsi` libraries either in jython or python. Do you know what I might be doing wrong and do you have any up to date installation scripts for this package? 

I am using Python 3 currently which I know isn't officially supported.

**Comment by mapio** [comment]
> However, I can't import any of the it.unimi.dsi libraries either in jython or python. Do you know what I might be doing wrong and do you have any up to date installation scripts for this package?

Nope… the package is quite old. Some people from “Common crawl" is working on it, but I’ve not touched it in a while.

> I am using Python 3 currently which I know isn't officially supported.

Not sure there is a version of Python 3 of Jython, but surely you must use a Java based interpreter if you want to be able to import LAW Javas libraries. 

What is the exact error reported by the interpreter?

**Comment by raulpuric** [comment]
It seems to be just a standard import error:

```(base) root@webgraph-test-0-0:~/installs$ java -jar jython/jython.jar
Jython 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[OpenJDK 64-Bit Server VM (Ubuntu)] on java11.0.7
Type "help", "copyright", "credits" or "license" for more information.
>>> from java.lang import Exception as JException
>>> from it.unimi.dsi.webgraph import ImmutableGraph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named it

**Comment by mapio** [comment]
Give a look to the last commit (linked above). The issue could be that you are not setting the classpath correctly…
